AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'eventportal-backend

  Sample SAM Template for eventportal-backend

  '
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
Resources:
  EventPortalWorkingTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/ApiWorkingTest/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        WorkingTest:
          Type: Api
          Properties:
            Path: /api_work_test
            Method: get
    Metadata:
      SamResourceId: EventPortalWorkingTest
  EventportalPostSpeaker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/AddingProposal/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        AddProposal:
          Type: Api
          Properties:
            Path: /adding_proposal
            Method: post
    Metadata:
      SamResourceId: EventportalPostSpeaker
  DynamoDbSpeechTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: "DynamoDbSpeechTable"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:
  EventportalBackendWorkingApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api_work_test/
  EventportalPostProposalApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/adding_proposal/
  EventPortalWorkingTest:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - EventPortalWorkingTest
      - Arn
  EventPortalWorkingTestIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - EventPortalWorkingTestRole
      - Arn
  EventportalPostSpeaker:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - EventportalPostSpeaker
      - Arn
  EventportalPostSpeakerIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - EventportalPostSpeakerRole
      - Arn
